HIRELINGS = HIRELINGS or {}
PLAYER_HIRELINGS = PLAYER_HIRELINGS or {}
HIRELING_OUTFIT_CHANGING = HIRELING_OUTFIT_CHANGING or {}

HIRELING_LAMP = 29432
HIRELING_MAX_PER_PLAYER = 10

-- The five trades open a whole section of the window each.
--
-- (!) The string is a kv key as well as the name the hireling says out loud.
-- Renaming one silently forgets every hireling that already had that job.
HIRELING_SKILLS = {
	BANKER = { 1001, "banker" },
	COOKING = { 1002, "cooker" },
	STEWARD = { 1003, "steward" },
	TRADER = { 1004, "trader" },
	CRAFTER = { 1005, "rune crafter" },
}

HIRELING_OUTFITS = {
	BANKER = { 2001, "banker" },
	COOKING = { 2002, "cooker" },
	STEWARD = { 2003, "steward" },
	TRADER = { 2004, "trader" },
	SERVANT = { 2005, "servant" },
	HYDRA = { 2006, "hydra" },
	FERUMBRAS = { 2007, "ferumbras" },
	BONELORD = { 2008, "bonelord" },
	DRAGON = { 2009, "dragon" },
}

HIRELING_OUTFIT_ORDER = {
	"BANKER",
	"TRADER",
	"COOKING",
	"STEWARD",
	"SERVANT",
	"HYDRA",
	"FERUMBRAS",
	"BONELORD",
	"DRAGON",
}

HIRELING_SEX = {
	FEMALE = PLAYERSEX_FEMALE or 0,
	MALE = PLAYERSEX_MALE or 1,
}

HIRELING_OUTFIT_DEFAULT = { name = "Citizen", female = 1107, male = 1108 }

HIRELING_OUTFITS_TABLE = {
	BANKER = { name = "Banker Dress", female = 1109, male = 1110 },
	BONELORD = { name = "Bonelord Dress", female = 1123, male = 1124 },
	COOKING = { name = "Cook Dress", female = 1113, male = 1114 },
	DRAGON = { name = "Dragon Dress", female = 1125, male = 1126 },
	FERUMBRAS = { name = "Ferumbras Dress", female = 1131, male = 1132 },
	HYDRA = { name = "Hydra Dress", female = 1129, male = 1130 },
	SERVANT = { name = "Servant Dress", female = 1117, male = 1118 },
	STEWARD = { name = "Steward Dress", female = 1115, male = 1116 },
	TRADER = { name = "Trader Dress", female = 1111, male = 1112 },
}

HIRELING_OUTFIT_STORE_OFFERS = {
	banker = 12001,
	trader = 12002,
	cooker = 12003,
	steward = 12004,
	servant = 12005,
	hydra = 12006,
	ferumbras = 12007,
	bonelord = 12008,
	dragon = 12009,
}

-- ─────────────────────────── name signs ───────────────────────────
--
-- Purely cosmetic, and deliberately narrow: a sign restyles the line the world
-- draws over ONE hireling's head and nothing else. The battle list builds its
-- own label from the creature's name, so it keeps the plain name for free --
-- which is exactly the ask: different in the house, the same everywhere else.
--
-- Two client calls do the whole job, and both are already bound to Lua
-- (src/client/luafunctions_client.cpp), so no binary rebuild is involved:
--
--   Creature:setTitle(ornament, font, colour)  -- an extra line ABOVE the name
--   Creature:setInformationColor(colour)       -- the name's own colour
--
-- (!) The ornaments are ASCII on purpose. Creature text is drawn with the
-- client's bitmap cp1252 font sheets, and anything outside them draws as a
-- gap rather than as a glyph.
--
-- `colour` is the ink the NAME is written in, chosen to sit legibly on that
-- plaque's face rather than to be pretty on its own -- pale on the dark
-- materials, warm on the light ones.
--
-- (!) The client hides the engine's own name (alpha 0) and writes the name
-- into the plaque instead, so this colour is NOT setInformationColor's old
-- job of tinting the name and the health bar together. NPC health bars are
-- switched off outright now; see GameHideNpcNames in the client module.
--
-- A sign is bought as an ITEM and used on ONE hireling, exactly like a job
-- contract: the right to wear it belongs to that hireling and to no other,
-- so giving Bella the oak board leaves Rufus as he was. Dresses are still
-- per character, because those are bought once and shared -- the difference is
-- deliberate and it is the difference between a wardrobe and a contract.
--
-- `item` is the physical sign, and `plaque` names the picture the client
-- hangs: modules/game_hireling/hireling.lua turns it into
-- /images/game/hirelings/plaque_<plaque>.png, generated by
-- tools/gen_hireling_plaques.js. The two must agree, and
-- tools/test_hireling_store.lua checks that every key here has an image.
--
-- The item ids are repurposed ones that were free by id AND by name
-- (tools/binary/findcontracts.js) and already carried the two flags an item
-- needs to be used on a creature. The store offer is a plain "item" offer, so
-- the card draws the item itself.
HIRELING_SIGNS = {
	{ id = 0, key = "none", name = "No sign", plaque = "", colour = 0xFFFFFF, offer = 0, item = 0 },
	{ id = 1, key = "oak", name = "Oak Board", plaque = "oak", colour = 0xF2DCB8, offer = 5130, item = 37407 },
	{ id = 2, key = "iron", name = "Iron Plate", plaque = "iron", colour = 0xDFE7EF, offer = 5131, item = 37406 },
	{ id = 3, key = "frost", name = "Frost Slab", plaque = "frost", colour = 0xE8F8FF, offer = 5132, item = 37334 },
	{ id = 4, key = "brass", name = "Brass Plaque", plaque = "brass", colour = 0xFFEAA8, offer = 5133, item = 37409 },
	{ id = 5, key = "marble", name = "Rose Marble", plaque = "marble", colour = 0xFFF0F4, offer = 5134, item = 37333 },
	{ id = 6, key = "ember", name = "Emberstone", plaque = "ember", colour = 0xFFB066, offer = 5135, item = 37312 },
	{ id = 7, key = "verdant", name = "Verdant Vine", plaque = "verdant", colour = 0xCDF0A6, offer = 5136, item = 37408 },
	{ id = 8, key = "velvet", name = "Royal Velvet", plaque = "velvet", colour = 0xE6CCFF, offer = 5137, item = 37321 },
}

HIRELING_SIGNS_BY_ID = {}
HIRELING_SIGNS_BY_KEY = {}
for _, sign in ipairs(HIRELING_SIGNS) do
	HIRELING_SIGNS_BY_ID[sign.id] = sign
	HIRELING_SIGNS_BY_KEY[sign.key] = sign
end

function GetHirelingSign(id)
	return HIRELING_SIGNS_BY_ID[tonumber(id) or -1]
end

function GetHirelingSignByOffer(offerId)
	for _, sign in ipairs(HIRELING_SIGNS) do
		if sign.offer ~= 0 and sign.offer == offerId then
			return sign
		end
	end
	return nil
end

function GetHirelingSignByItem(itemId)
	for _, sign in ipairs(HIRELING_SIGNS) do
		if sign.item ~= 0 and sign.item == itemId then
			return sign
		end
	end
	return nil
end

HIRELING_FOODS_BOOST = {
	MAGIC = 29410,
	MELEE = 29411,
	SHIELDING = 29408,
	DISTANCE = 29409,
}

HIRELING_FOODS_IDS = {
	29412,
	29413,
	29414,
	29415,
	29416,
}

local function hirelingSystemEnabled()
	-- The config flag is the design decision; the tuning knob is the circuit
	-- breaker the console can throw at two in the morning without a restart.
	if Tuning and not Tuning.enabled("feature.hirelings") then
		return false
	end
	return configManager and configKeys and configKeys.HIRELING_SYSTEM_ENABLED and
		configManager.getBoolean(configKeys.HIRELING_SYSTEM_ENABLED)
end

local function astraHirelingProtocolEnabled(player)
	return hirelingSystemEnabled() and configKeys.ASTRA_HIRELING_PROTOCOL_ENABLED and
		configManager.getBoolean(configKeys.ASTRA_HIRELING_PROTOCOL_ENABLED) and
		player and player.isUsingAstraClient and player:isUsingAstraClient()
end

local function logWarning(message)
	if logger and logger.warn then
		logger.warn(message)
	else
		print(message)
	end
end

local function logError(message)
	if logger and logger.error then
		logger.error(message)
	else
		print(message)
	end
end

local function makeHirelingLampDescription(hireling)
	return "This mysterious lamp summons your very own personal hireling.\nThis item cannot be traded.\nThis magic lamp is the home of " ..
		hireling:getName() .. "."
end

local function isValidHirelingName(name)
	name = tostring(name or ""):gsub("^%s*(.-)%s*$", "%1")
	if #name < 3 or #name > 20 or name:find("  ", 1, true) then
		return false
	end

	for i = 1, #name do
		local char = name:sub(i, i)
		if not char:match("[A-Za-z ]") then
			return false
		end
	end
	return true
end

local function formatHirelingName(name)
	name = tostring(name or ""):gsub("^%s*(.-)%s*$", "%1"):lower()
	return (name:gsub("(%a)([%w']*)", function(first, rest)
		return first:upper() .. rest:lower()
	end))
end

-- (getOwnerPlayer/releaseOwnerPlayer lived here. Removed 2026-09-11: every
-- caller now reads the owner's kv by GUID -- see ownerKV. The release step
-- called player:remove() on a character loaded from the database, which for
-- a Player is kickPlayer(true) on someone who is not in the world.)

local function decorateHirelingLamp(lamp, hireling)
	lamp:setAttribute(ITEM_ATTRIBUTE_DESCRIPTION, makeHirelingLampDescription(hireling))
	lamp:setCustomAttribute("Hireling", hireling:getId())
	return lamp
end

local function addHirelingLampToInbox(player, hireling)
	local inbox = player and player:getStoreInbox()
	if not inbox then
		return nil
	end

	local lamp = inbox:addItem(HIRELING_LAMP, 1, INDEX_WHEREEVER, FLAG_NOLIMIT)
	if not lamp then
		return nil
	end

	return decorateHirelingLamp(lamp, hireling)
end

-- Hand the lamp over directly, for an NPC giving it to you face to face.
--
-- The lamp is `movable="0"`, so it can never be a chest reward -- the player
-- would not be able to pick it up. It also is not a generic item: each lamp
-- carries a custom attribute naming one database row, and a lamp without that
-- attribute deletes itself with an error when used. So a quest has to CREATE
-- the hireling and hand over the lamp it gets back, which is what
-- Player:addNewHireling does.
--
-- Falls back to the Store Inbox when the backpack cannot take it, so a full
-- or overloaded player never loses a quest reward.
local function addHirelingLampToPlayer(player, hireling)
	local lamp = player:addItem(HIRELING_LAMP, 1)
	if lamp then
		return decorateHirelingLamp(lamp, hireling), "backpack"
	end

	local inboxLamp = addHirelingLampToInbox(player, hireling)
	if inboxLamp then
		return inboxLamp, "inbox"
	end
	return nil
end

local function persistHirelingReturn(owner, hireling)
	local previousState = {
		active = hireling.active,
		cid = hireling.cid,
		position = {
			x = hireling.posx,
			y = hireling.posy,
			z = hireling.posz
		}
	}
	local lamp
	local committed = false
	local failureReason = "Failed to return the hireling to its lamp."

	local ok, err = pcall(function()
		lamp = addHirelingLampToInbox(owner, hireling)
		if not lamp then
			failureReason = "You don't have enough room in your store inbox."
			return
		end

		hireling.active = 0
		hireling.cid = -1
		hireling:setPosition({ x = 0, y = 0, z = 0 })

		if not hireling:save() then
			return
		end

		if not owner.save or not owner:save() then
			return
		end

		committed = true
	end)

	if committed then
		return true
	end

	local lampRollbackOk = pcall(function()
		if lamp and lamp.remove then
			lamp:remove()
		end
	end)
	local stateRollbackOk = pcall(function()
		hireling.active = previousState.active
		hireling.cid = previousState.cid
		hireling:setPosition(previousState.position)
	end)

	local hirelingRollbackOk, hirelingRollbackResult = pcall(function()
		return hireling:save()
	end)
	local ownerRollbackOk, ownerRollbackResult = pcall(function()
		return owner.save and owner:save()
	end)

	if not lampRollbackOk or not stateRollbackOk or not hirelingRollbackOk or not hirelingRollbackResult or
		not ownerRollbackOk or not ownerRollbackResult then
		logError("[Hireling] Failed to persist rollback while returning hireling id " .. tostring(hireling:getId()) .. ".")
	end
	if not ok then
		logError("[Hireling] Failed to return hireling id " .. tostring(hireling:getId()) .. ": " .. tostring(err))
	end
	return false, failureReason
end

-- One NPC type per hireling, keyed by Hireling:getSpawnKey(). The type is
-- registered ONCE (Game.createNpcType only works from the Scripts or Npc
-- interface, so it has to happen at startup or from the lamp action) and its
-- display name is changed in place on rename -- see Hireling:renameForCoins.
HIRELING_NPC_TYPES = HIRELING_NPC_TYPES or {}

local function ensureHirelingNpcType(npcName, displayName)
	if HIRELING_NPC_TYPES[npcName] then
		return true
	end

	if not createHirelingType then
		local ok, err = pcall(dofile, "data/npc/crystalserver/shops/mixed/hireling.lua")
		if not ok then
			logError("[Hireling] Failed to load Crystal hireling NPC: " .. tostring(err))
			return false
		end
	end

	if not createHirelingType then
		logError("[Hireling] createHirelingType is not available.")
		return false
	end

	local ok, err = pcall(createHirelingType, npcName, displayName)
	if not ok then
		logError("[Hireling] Failed to register NPC type " .. npcName .. ": " .. tostring(err))
		return false
	end
	return true
end

-- `active` in player_hirelings: 0 in his lamp, 1 standing in a house, and 2
-- "in his lamp, but the lamp is still owed". The third state exists because
-- a hireling can have to leave the house while his owner is OFFLINE (the
-- house changed hands, or the house check failed at startup), and an offline
-- player has no Store Inbox to put a lamp into. Before this state existed
-- the return simply failed, the row stayed at 1 with no creature and no
-- lamp anywhere, and the owner had no way to get him back. The lamp is
-- delivered by Player:claimOwedHirelingLamps() on the owner's next login.
HIRELING_ACTIVE_LAMP_OWED = 2

local function parkHirelingLampOwed(hireling, why)
	local npc = hireling.cid and hireling.cid > 0 and Npc(hireling.cid) or nil
	hireling.active = HIRELING_ACTIVE_LAMP_OWED
	hireling.cid = -1
	hireling:setPosition({ x = 0, y = 0, z = 0 })
	if not hireling:save() then
		logError("[Hireling] Could not park hireling id " .. tostring(hireling:getId()) .. " (" .. tostring(why) .. ").")
		return false
	end
	if npc then
		npc:remove()
	end
	logWarning("[Hireling] Hireling id " .. tostring(hireling:getId()) .. " (" .. hireling:getName() ..
		") sent to his lamp while the owner is offline: " .. tostring(why) .. ". Lamp owed on next login.")
	return true
end

local function returnHirelingToOwnerInbox(hireling, why)
	if not hireling then
		return false
	end

	local owner = Player(hireling:getOwnerId())
	if not owner then
		return parkHirelingLampOwed(hireling, why)
	end

	local npc = hireling.cid and Npc(hireling.cid) or nil
	local returned = persistHirelingReturn(owner, hireling)
	if not returned then
		-- Online but no room in the inbox: park him, the login/claim path
		-- retries. Losing the creature beats stranding the row at active=1.
		return parkHirelingLampOwed(hireling, tostring(why) .. "; inbox delivery failed")
	end

	if npc then
		npc:remove()
	end
	owner:sendTextMessage(MESSAGE_EVENT_ADVANCE, hireling:getName() .. " has returned to the lamp in your Store Inbox.")
	return true
end

local function checkHouseAccess(hireling)
	if not hireling or hireling.active ~= 1 then
		return false
	end

	local position = hireling:getPosition()
	local tile = position:getTile()
	local house = tile and tile:getHouse()
	if not house then
		returnHirelingToOwnerInbox(hireling, "no house at " .. tostring(position))
		return false
	end

	if house:getOwnerGuid() == hireling:getOwnerId() then
		return true
	end

	returnHirelingToOwnerInbox(hireling, string.format("house %d owned by %d, hireling owned by %d",
		house:getId(), house:getOwnerGuid(), hireling:getOwnerId()))
	return false
end

local function spawnHirelings()
	if not hirelingSystemEnabled() then
		return
	end

	for _, hireling in ipairs(HIRELINGS) do
		if checkHouseAccess(hireling) then
			hireling:spawn()
		end
	end
end

Hireling = Hireling or {
	id = -1,
	player_id = -1,
	name = "hireling",
	active = 0,
	sex = HIRELING_SEX.MALE,
	posx = 0,
	posy = 0,
	posz = 0,
	lookbody = 34,
	lookfeet = 116,
	lookhead = 97,
	looklegs = 3,
	looktype = 1108,
	cid = -1,
}

function Hireling:new(o)
	o = o or {}
	setmetatable(o, self)
	self.__index = self
	return o
end

function Hireling:getOwnerId()
	return self.player_id
end

function Hireling:getId()
	return self.id
end

function Hireling:getName()
	return self.name
end

-- The NPC type's key never changes; only its display name does. That is what
-- makes a rename possible from a network handler at all: Game.createNpcType
-- refuses to run outside the Scripts/Npc interfaces (the previous version
-- built a NEW type per rename and every rename failed with exactly that
-- error), whereas NpcType:name() and Game.createNpc work from anywhere.
function Hireling:getSpawnKey()
	return "Hireling " .. self:getId()
end

-- 100 BPC (owner, 2026-10-04; 25 before, 10 before that). A name is the one thing about a
-- hireling everyone else sees, and the price should say so.
HIRELING_RENAME_COST = 100

function Hireling:renameForCoins(player, name)
	if self:getOwnerId() ~= player:getGuid() or not self:canTalkTo(player) or self._returning then
		return false, "Only the owner can rename this hireling."
	end
	name = formatHirelingName(name)
	if not isValidHirelingName(name) then return false, "Use 3 to 20 letters, with single spaces between words." end
	if name == self.name then return false, "That is already my name. No coins were spent." end

	local oldNpc = Npc(self.cid)
	local npcType = HIRELING_NPC_TYPES[self:getSpawnKey()]
	if not oldNpc or not npcType then return false, "Unable to change the name. No coins were spent." end

	local oldName = self.name
	local ok = Coins.move(player:getAccountId(), -HIRELING_RENAME_COST, "spend.hireling_name",
		{type = "hireling", id = self:getId()}, {oldName = oldName, newName = name}, player:getGuid(), function()
			if not db.query("UPDATE `player_hirelings` SET `name`=" .. db.escapeString(name) ..
				" WHERE `id`=" .. self:getId() .. " AND `player_id`=" .. player:getGuid()) or db.affectedRows() ~= 1 then
				error("Hireling name update failed")
			end
		end)
	if not ok then
		return false, string.format("Renaming costs %d BPC. The payment could not be completed; no name change was made.", HIRELING_RENAME_COST)
	end

	-- Paid and persisted. A creature's name is copied from its type when it is
	-- created, so rename the type and stand up a fresh creature; the old one
	-- goes once the new one exists, so he is never absent from the house.
	self.name = name
	npcType:name(name)
	local replacement = Game.createNpc(self:getSpawnKey(), self:getPosition(), false, true, CONST_ME_NONE)
	if not replacement then
		-- Persisted under the new name; he answers to it after the next
		-- summon or server save. Not worth refunding over.
		logWarning("[Hireling] Renamed hireling " .. self:getId() .. " but could not respawn the creature.")
		return true
	end
	replacement:setOutfit(self:getOutfit())
	replacement:setSpeechBubble(SPEECHBUBBLE_HIRELING or 7)
	self:setCreature(replacement)
	oldNpc:remove()
	return true
end

function Hireling:canTalkTo(player)
	if not player or self.active ~= 1 then
		return false
	end

	if Position.getDistanceBetween(player:getPosition(), self:getPosition()) > 3 then
		return false
	end

	local playerTile = player:getPosition():getTile()
	local playerHouse = playerTile and playerTile:getHouse()
	local hirelingTile = self:getPosition():getTile()
	local hirelingHouse = hirelingTile and hirelingTile:getHouse()
	return playerHouse and hirelingHouse and playerHouse:getId() == hirelingHouse:getId()
end

function Hireling:getPosition()
	return Position(self.posx, self.posy, self.posz)
end

function Hireling:setPosition(pos)
	self.posx = pos.x
	self.posy = pos.y
	self.posz = pos.z
end

function Hireling:getOutfit()
	return {
		lookType = self.looktype,
		lookHead = self.lookhead,
		lookBody = self.lookbody,
		lookLegs = self.looklegs,
		lookFeet = self.lookfeet,
		lookAddons = 0,
		lookMount = 0,
	}
end

function Hireling:getAvailableOutfits(includeLocked)
	local player = Player(self:getOwnerId())
	local sex = self.sex == HIRELING_SEX.FEMALE and "female" or "male"
	-- Each entry carries BOTH sexes' look types so the wardrobe can preview a
	-- dress on either build and switch sex without a second round trip.
	-- `lookType` is the one for the hireling's current sex.
	local outfitsAvailable = {
		{ name = HIRELING_OUTFIT_DEFAULT.name, lookType = HIRELING_OUTFIT_DEFAULT[sex],
			female = HIRELING_OUTFIT_DEFAULT.female, male = HIRELING_OUTFIT_DEFAULT.male, storeOffer = 0 },
	}

	if not player then
		return outfitsAvailable
	end

	for _, key in ipairs(HIRELING_OUTFIT_ORDER) do
		local outfitInfo = HIRELING_OUTFITS[key]
		local outfitName = outfitInfo and outfitInfo[2]
		local outfitTable = HIRELING_OUTFITS_TABLE[key]
		if outfitName and outfitTable then
			local haveOutfit = player:kv():scoped("hireling-outfits"):get(outfitName) == true
			if haveOutfit or includeLocked then
				outfitsAvailable[#outfitsAvailable + 1] = {
					name = outfitTable.name,
					lookType = outfitTable[sex],
					female = outfitTable.female,
					male = outfitTable.male,
					storeOffer = haveOutfit and 0 or (HIRELING_OUTFIT_STORE_OFFERS[outfitName] or 0),
				}
			end
		end
	end
	return outfitsAvailable
end

-- Everything the wardrobe can change, applied together: sex, dress and the
-- four colours. `lookType` must be the requested sex's look of a dress the
-- owner has (the citizen outfit is always owned). Returns false plus a
-- reason the hireling can say out loud.
function Hireling:setAppearance(player, sex, lookType, colours)
	if not player or self:getOwnerId() ~= player:getGuid() or not self:canTalkTo(player) then
		return false, "Only my master may dress me."
	end
	if sex ~= HIRELING_SEX.FEMALE and sex ~= HIRELING_SEX.MALE then
		return false, "I do not know that shape."
	end

	local dress
	for _, outfitData in ipairs(self:getAvailableOutfits(true)) do
		local matches = outfitData.female == lookType or outfitData.male == lookType
		if matches and (outfitData.storeOffer or 0) == 0 then
			dress = outfitData
			break
		elseif matches then
			return false, "I do not own that dress. You can buy dresses for me in the store."
		end
	end
	if not dress then
		return false, "I do not own that dress."
	end

	local outfit = self:getOutfit()
	outfit.lookType = sex == HIRELING_SEX.FEMALE and dress.female or dress.male
	for _, key in ipairs({ "lookHead", "lookBody", "lookLegs", "lookFeet" }) do
		local value = tonumber(colours and colours[key]) or outfit[key]
		if value < 0 or value > 132 then
			return false, "That is not a colour I know."
		end
		outfit[key] = value
	end

	local creature = Creature(self.cid)
	if not creature then
		return false, "I cannot change right now."
	end

	self.sex = sex
	creature:setOutfit(outfit)
	self:setOutfit(outfit)
	self:save()
	return true
end

-- The OWNER's kv scope, reached by GUID rather than through a Player object.
--
-- kv.scoped("player"):scoped(guid) is byte-for-byte the scope player:kv()
-- builds in C++ (luaPlayerKV: KVStore "player" -> fmt "{}" of the GUID), and
-- KVStore::get loads any key from `kv_store` on a cache miss -- so this reads
-- an OFFLINE owner's values exactly, with no character load at all.
--
-- (!) "%d", not tostring: C++ writes the GUID segment as an integer, and in
-- Lua 5.5 tostring of a float GUID is "123.0" -- a different key, read as
-- empty. The hireling-id segment below keeps tostring because that is how
-- every key already in the store was written.
local function ownerKV(ownerGuid)
	return kv.scoped("player"):scoped(string.format("%d", ownerGuid))
end

-- Signs live under the OWNER's kv keyed by hireling id, the same shape jobs
-- and the workshop use, because a hireling has no kv of its own. Two scopes:
-- which signs this hireling has been GIVEN, and which one he is WEARING.
local function hirelingSignStore(ownerGuid, hirelingId)
	return ownerKV(ownerGuid):scoped("hireling-worn-signs"):scoped(tostring(hirelingId))
end

local function hirelingSignRights(ownerGuid, hirelingId)
	return ownerKV(ownerGuid):scoped("hireling-signs"):scoped(tostring(hirelingId))
end

-- Does this hireling have the right to wear that sign? Granted by using the
-- sign item on him -- see data/scripts/actions/items/hireling_signs.lua.
function Hireling:hasSign(signKey)
	local sign = HIRELING_SIGNS_BY_KEY[signKey]
	if not sign then
		return false
	end
	if sign.plaque == "" then
		return true -- "No sign" is not something you buy
	end

	return hirelingSignRights(self:getOwnerId(), self:getId()):get(signKey) == true
end

-- Returns false when he already had it, so the caller can refuse to consume
-- the item before it is spent -- the same contract the job contracts keep.
function Hireling:grantSign(player, signKey)
	if not player or self:getOwnerId() ~= player:getGuid() then
		return false
	end
	local sign = HIRELING_SIGNS_BY_KEY[signKey]
	if not sign or sign.item == 0 then
		return false
	end

	local store = hirelingSignRights(self:getOwnerId(), self:getId())
	if store:get(signKey) == true then
		return false
	end
	store:set(signKey, true)
	return true
end

-- Every sign this hireling may wear, "No sign" first. The window sends this so
-- the wardrobe picker lists exactly what he can actually be given.
function Hireling:getSigns()
	local out = {}
	for _, sign in ipairs(HIRELING_SIGNS) do
		out[#out + 1] = { sign = sign, owned = self:hasSign(sign.key) }
	end
	return out
end

-- Read straight from the store by the owner's GUID, and NOT cached.
--
-- (!) This used to load the owner through getOwnerPlayer -- the whole
-- character, from the database, whenever he was offline -- and because that
-- was expensive the answer was memoised on the Lua object for the rest of the
-- boot. Any read that came back without a player cached 0, and nothing but a
-- fresh setSign ever cleared it. Signs are read for every hireling whenever
-- ANYONE logs in, so after a restart the first player in decided every sign
-- in the world. Owner-reported 2026-09-11 as "the plaque is lost on relog":
-- Sorcerer Harding logged in three times after the 07:20 boot before GM
-- Harding, King Winston's owner, did.
--
-- With the load gone there is nothing left worth caching: a KV get is an
-- in-memory lookup after its first miss.
function Hireling:getSignId()
	local key = hirelingSignStore(self:getOwnerId(), self:getId()):get("sign")
	local sign = type(key) == "string" and HIRELING_SIGNS_BY_KEY[key]
	return sign and sign.id or 0
end

-- Owner-only, and refuses a sign the character has not bought. Returns false
-- plus a reason the hireling can say out loud.
function Hireling:setSign(player, signId)
	if not player or self:getOwnerId() ~= player:getGuid() or not self:canTalkTo(player) then
		return false, "Only my master may choose my sign."
	end

	local sign = GetHirelingSign(signId)
	if not sign then
		return false, "I do not know that sign."
	end
	if not self:hasSign(sign.key) then
		return false, "Nobody has given me that sign. Use one on me and I will hang it."
	end

	hirelingSignStore(self:getOwnerId(), self:getId()):set("sign", sign.key)
	return true
end

function Hireling:requestOutfitChange()
	local player = Player(self:getOwnerId())
	if not player then
		return false
	end

	HIRELING_OUTFIT_CHANGING[self:getOwnerId()] = self:getId()
	return player:sendHirelingOutfitWindow(self)
end

function Hireling:hasOutfit(lookType)
	for _, outfit in ipairs(self:getAvailableOutfits(false)) do
		if outfit.lookType == lookType then
			return true
		end
	end
	return false
end

function Hireling:setOutfit(outfit)
	self.looktype = outfit.lookType
	self.lookhead = outfit.lookHead
	self.lookbody = outfit.lookBody
	self.looklegs = outfit.lookLegs
	self.lookfeet = outfit.lookFeet
end

function Hireling:changeOutfit(player, outfit)
	HIRELING_OUTFIT_CHANGING[self:getOwnerId()] = nil
	if not player or self:getOwnerId() ~= player:getGuid() or not self:canTalkTo(player) then
		return false
	end

	if not self:hasOutfit(outfit.lookType) then
		return false
	end

	local creature = Creature(self.cid)
	if not creature then
		return false
	end

	creature:setOutfit(outfit)
	self:setOutfit(outfit)
	self:save()
	return true
end

-- Jobs are stored PER HIRELING, not per character.
--
-- They used to hang off the owner's kv directly, so one purchase taught every
-- hireling that character owned. That was defensible while jobs came from the
-- store as an account-wide unlock. It is wrong now that a job arrives as a
-- physical contract the player uses on one specific hireling: handing a
-- contract to Bella and watching Rufus learn to cook makes the item a lie.
--
-- The scope is still the OWNER's kv (hirelings have no kv of their own), just
-- keyed by hireling id underneath. Dresses stay per character on purpose --
-- those are bought in the store and apply to everyone you own.
local function hirelingSkillStore(ownerGuid, hirelingId)
	return ownerKV(ownerGuid):scoped("hireling-skills"):scoped(tostring(hirelingId))
end

-- By GUID for the same reason as Hireling:getSignId. This one is asked by the
-- DIALOGUE, so every visitor who talked to a hireling whose owner was offline
-- used to load that owner's whole character -- and then kick it.
function Hireling:hasSkill(skillName)
	return hirelingSkillStore(self:getOwnerId(), self:getId()):get(skillName) == true
end

-- Which shop categories this hireling will open, in ONE place: the dialogue,
-- the window's Goods list and the packet that greys its rows all ask here, so
-- what he says and what the window shows cannot drift apart.
--
-- "various" is his own odds and ends and is open to everyone, trade or no
-- trade -- that has always been true and is the reason Goods is never a fully
-- locked section. Everything else needs the trader's contract.
function Hireling:canSellCategory(category)
	category = tostring(category or ""):lower()
	if category == "" then
		return false
	end
	if category == "various" then
		return true
	end
	return self:hasSkill(HIRELING_SKILLS.TRADER[2])
end

-- Returns false when the hireling already had the job, so callers can tell a
-- wasted contract from a successful one before consuming the item.
function Hireling:enableSkill(skillName)
	local store = hirelingSkillStore(self:getOwnerId(), self:getId())
	if store:get(skillName) == true then
		return false
	end
	store:set(skillName, true)
	return true
end

function Hireling:setCreature(creature)
	if type(creature) == "number" then
		self.cid = creature
	elseif creature and creature.getId then
		self.cid = creature:getId()
	end
end

function Hireling:save()
	if self.id <= 0 then
		return false
	end

	local sql = "UPDATE `player_hirelings` SET"
	sql = sql .. " `name`=" .. db.escapeString(self.name)
	sql = sql .. ", `active`=" .. tostring(self.active)
	sql = sql .. ", `sex`=" .. tostring(self.sex)
	sql = sql .. ", `posx`=" .. tostring(self.posx)
	sql = sql .. ", `posy`=" .. tostring(self.posy)
	sql = sql .. ", `posz`=" .. tostring(self.posz)
	sql = sql .. ", `lookbody`=" .. tostring(self.lookbody)
	sql = sql .. ", `lookfeet`=" .. tostring(self.lookfeet)
	sql = sql .. ", `lookhead`=" .. tostring(self.lookhead)
	sql = sql .. ", `looklegs`=" .. tostring(self.looklegs)
	sql = sql .. ", `looktype`=" .. tostring(self.looktype)
	sql = sql .. " WHERE `id`=" .. tostring(self.id)
	return db.query(sql)
end

function Hireling:spawn()
	if not hirelingSystemEnabled() then
		return false
	end

	local npcName = self:getSpawnKey()
	if not ensureHirelingNpcType(npcName, self:getName()) then
		return false
	end

	-- The type may have been registered under an earlier name (a rename while
	-- he was in his lamp, or a server save in between); the creature copies
	-- the type's name, so make sure it is current before he appears.
	local npcType = HIRELING_NPC_TYPES[npcName]
	if npcType and npcType:name() ~= self:getName() then
		npcType:name(self:getName())
	end

	self.active = 1
	local npc = Game.createNpc(npcName, self:getPosition(), false, true, CONST_ME_NONE)
	if not npc then
		self.active = 0
		return false
	end

	npc:setOutfit(self:getOutfit())
	npc:setSpeechBubble(SPEECHBUBBLE_HIRELING or 7)
	npc:getPosition():sendMagicEffect(CONST_ME_TELEPORT)
	self:setCreature(npc)
	self:save()

	-- His name sign is keyed by CREATURE id, and he has just been given a new
	-- one. Without this he stands there with a plain name until something else
	-- happens to rebroadcast. Guarded because the network script loads after
	-- this library, and the startup sweep spawns everyone before anyone is
	-- online (Game.getPlayers() is empty then, so this costs nothing).
	if HirelingWindow and HirelingWindow.broadcastSigns then
		HirelingWindow.broadcastSigns()
	end
	return true
end

function Hireling:returnToLamp(playerId)
	if self.active ~= 1 or self._returning then
		return false
	end

	local player = Player(playerId)
	if not player or self:getOwnerId() ~= playerId then
		if player then
			player:getPosition():sendMagicEffect(CONST_ME_POFF)
			player:sendTextMessage(MESSAGE_FAILURE, "You are not the master of this hireling.")
		end
		return false
	end

	self._returning = true
	local hirelingId = self:getId()
	local npcId = self.cid
	addEvent(function(ownerGuid, delayedHirelingId, delayedNpcId)
		local owner = Player(ownerGuid)
		local hireling = getHirelingById(delayedHirelingId)
		if not owner or not hireling then
			if hireling then
				hireling._returning = nil
			end
			return
		end

		local npc = Npc(delayedNpcId)
		local returned, failureReason = persistHirelingReturn(owner, hireling)
		if not returned then
			owner:getPosition():sendMagicEffect(CONST_ME_POFF)
			owner:sendTextMessage(MESSAGE_FAILURE, failureReason)
			hireling._returning = nil
			return
		end

		if npc then
			npc:say("As you wish!", TALKTYPE_PRIVATE_NP, false, owner, npc:getPosition())
			npc:getPosition():sendMagicEffect(CONST_ME_PURPLESMOKE)
			npc:remove()
		end

		hireling._returning = nil
	end, 1000, player:getGuid(), hirelingId, npcId)
	return true
end

function SaveHirelings()
	if not HIRELINGS then
		return true
	end

	for _, hireling in ipairs(HIRELINGS) do
		if not hireling:save() then
			logWarning("[Hireling] Failed to save hireling id " .. tostring(hireling:getId()))
		end
	end
	return true
end

function getHirelingById(id)
	id = tonumber(id)
	if not id then
		return nil
	end

	for _, hireling in ipairs(HIRELINGS) do
		if hireling:getId() == id then
			return hireling
		end
	end
	return nil
end

function getHirelingByPosition(position)
	if not position then
		return nil
	end

	for _, hireling in ipairs(HIRELINGS) do
		if hireling.active == 1 and hireling.posx == position.x and hireling.posy == position.y and hireling.posz == position.z then
			return hireling
		end
	end
	return nil
end

function getHirelingByCid(cid)
	cid = tonumber(cid)
	if not cid then
		return nil
	end

	for _, hireling in ipairs(HIRELINGS) do
		if hireling.cid == cid then
			return hireling
		end
	end
	return nil
end

function GetHirelingSkillNameById(id)
	id = tonumber(id)
	for _, skill in pairs(HIRELING_SKILLS) do
		if skill[1] == id then
			return skill[2]
		end
	end
	return nil
end

function GetHirelingOutfitNameById(id)
	id = tonumber(id)
	for _, outfit in pairs(HIRELING_OUTFITS) do
		if outfit[1] == id then
			return outfit[2]
		end
	end
	return nil
end

function HirelingsInit()
	if not hirelingSystemEnabled() then
		return true
	end

	if db.tableExists and not db.tableExists("player_hirelings") then
		logWarning("[Hireling] player_hirelings table is missing.")
		return false
	end

	HIRELINGS = {}
	PLAYER_HIRELINGS = {}
	HIRELING_OUTFIT_CHANGING = {}

	local rows = db.storeQuery("SELECT * FROM `player_hirelings`")
	if rows then
		repeat
			local playerId = result.getNumber(rows, "player_id")
			PLAYER_HIRELINGS[playerId] = PLAYER_HIRELINGS[playerId] or {}

			local hireling = Hireling:new()
			hireling.id = result.getNumber(rows, "id")
			hireling.player_id = playerId
			hireling.name = result.getString(rows, "name")
			hireling.active = result.getNumber(rows, "active")
			hireling.sex = result.getNumber(rows, "sex")
			hireling.posx = result.getNumber(rows, "posx")
			hireling.posy = result.getNumber(rows, "posy")
			hireling.posz = result.getNumber(rows, "posz")
			hireling.lookbody = result.getNumber(rows, "lookbody")
			hireling.lookfeet = result.getNumber(rows, "lookfeet")
			hireling.lookhead = result.getNumber(rows, "lookhead")
			hireling.looklegs = result.getNumber(rows, "looklegs")
			hireling.looktype = result.getNumber(rows, "looktype")
			hireling.cid = -1

			table.insert(PLAYER_HIRELINGS[playerId], hireling)
			table.insert(HIRELINGS, hireling)
		until not result.next(rows)
		result.free(rows)
	end

	spawnHirelings()
	return true
end

function PersistHireling(hireling)
	local query = string.format(
		"INSERT INTO `player_hirelings` (`player_id`,`name`,`active`,`sex`,`posx`,`posy`,`posz`,`lookbody`,`lookfeet`,`lookhead`,`looklegs`,`looktype`) VALUES (%d, %s, %d, %d, %d, %d, %d, %d, %d, %d, %d, %d)",
		hireling.player_id,
		db.escapeString(hireling.name),
		hireling.active,
		hireling.sex,
		hireling.posx,
		hireling.posy,
		hireling.posz,
		hireling.lookbody,
		hireling.lookfeet,
		hireling.lookhead,
		hireling.looklegs,
		hireling.looktype
	)

	if not db.query(query) then
		return false
	end

	hireling.id = db.lastInsertId()
	return hireling.id and hireling.id > 0
end

function Player:getHirelings()
	return PLAYER_HIRELINGS[self:getGuid()] or {}
end

function Player:getHirelingsCount()
	return #self:getHirelings()
end

function Player:hasHirelings()
	return self:getHirelingsCount() > 0
end

-- `deliverTo` picks where the lamp lands: "hand" for an NPC giving it to you
-- (backpack, falling back to the Store Inbox), anything else for the Store
-- Inbox. Quest NPCs want "hand"; keep the default so existing callers are
-- unaffected.
--
-- Returns the hireling on success, or false plus a message the caller can say
-- out loud. On any failure after the row is written, the row is deleted again,
-- so a failed hand-over can never leave an orphan hireling that the player
-- owns but has no lamp for.
function Player:addNewHireling(name, sex, deliverTo)
	if not hirelingSystemEnabled() then
		return false, "Hireling system is disabled."
	end

	name = formatHirelingName(name)
	if not isValidHirelingName(name) then
		return false, "You cannot use this hireling name."
	end

	if self:getHirelingsCount() >= HIRELING_MAX_PER_PLAYER then
		return false, "You already own the maximum amount of hirelings."
	end

	local hireling = Hireling:new()
	hireling.name = name
	hireling.player_id = self:getGuid()
	hireling.sex = tonumber(sex) == HIRELING_SEX.FEMALE and HIRELING_SEX.FEMALE or HIRELING_SEX.MALE
	hireling.looktype = hireling.sex == HIRELING_SEX.FEMALE and HIRELING_OUTFIT_DEFAULT.female or HIRELING_OUTFIT_DEFAULT.male

	if not PersistHireling(hireling) then
		return false, "Failed to save hireling."
	end

	local lamp, landedIn
	if deliverTo == "hand" then
		lamp, landedIn = addHirelingLampToPlayer(self, hireling)
	else
		lamp, landedIn = addHirelingLampToInbox(self, hireling), "inbox"
	end

	if not lamp then
		db.query("DELETE FROM `player_hirelings` WHERE `id`=" .. hireling:getId())
		return false, "You have no room for the lamp."
	end

	PLAYER_HIRELINGS[self:getGuid()] = PLAYER_HIRELINGS[self:getGuid()] or {}
	table.insert(PLAYER_HIRELINGS[self:getGuid()], hireling)
	table.insert(HIRELINGS, hireling)
	-- Third return says where the lamp actually landed ("backpack" or "inbox")
	-- so a quest NPC can tell the player where to look for it.
	return hireling, nil, landedIn
end

function Player:isChangingHirelingOutfit()
	return (HIRELING_OUTFIT_CHANGING[self:getGuid()] or 0) > 0
end

function Player:getHirelingChangingOutfit()
	return getHirelingById(HIRELING_OUTFIT_CHANGING[self:getGuid()])
end

function Player:sendHirelingOutfitWindow(hireling)
	if not astraHirelingProtocolEnabled(self) or not hireling then
		return false
	end

	local outfit = hireling:getOutfit()
	local msg = NetworkMessage()
	msg:addByte(0xC8)
	msg:addU16(outfit.lookType)
	if outfit.lookType == 0 then
		msg:addU16(outfit.lookTypeEx or 0)
	else
		msg:addByte(outfit.lookHead)
		msg:addByte(outfit.lookBody)
		msg:addByte(outfit.lookLegs)
		msg:addByte(outfit.lookFeet)
		msg:addByte(outfit.lookAddons)
	end
	msg:addU16(outfit.lookMount or 0)
	msg:addU16(0) -- familiar looktype (Astra outfit extension)

	local availableOutfits = hireling:getAvailableOutfits(true)
	msg:addByte(math.min(#availableOutfits, 255))
	local storeOffers = {}
	for i = 1, math.min(#availableOutfits, 255) do
		local outfitData = availableOutfits[i]
		msg:addU16(outfitData.lookType)
		msg:addString(outfitData.name)
		msg:addByte(0)
		if outfitData.storeOffer and outfitData.storeOffer > 0 then
			storeOffers[#storeOffers + 1] = { outfitData.lookType, outfitData.storeOffer }
		end
	end

	msg:addByte(0) -- mount count

	msg:addByte(0x48) -- H
	msg:addByte(0x52) -- R
	msg:addByte(0x4C) -- L
	msg:addByte(0x47) -- G
	msg:addU32(hireling.cid > 0 and hireling.cid or 0)
	msg:addByte(hireling.sex)
	msg:addU16(math.min(#storeOffers, 255))
	for i = 1, math.min(#storeOffers, 255) do
		msg:addU16(storeOffers[i][1])
		msg:addU32(storeOffers[i][2])
	end
	msg:addByte(0) -- try-on pair count

	return msg:sendToPlayer(self)
end

-- Deliver every lamp this character is owed (see HIRELING_ACTIVE_LAMP_OWED).
-- Also heals the older failure mode directly: a row at active=1 with no
-- creature behind it after startup is a hireling nobody can reach, so he is
-- treated as owed too. Returns how many lamps were handed over.
function Player:claimOwedHirelingLamps()
	local delivered = 0
	for _, hireling in ipairs(self:getHirelings()) do
		local stranded = hireling.active == 1 and (not hireling.cid or hireling.cid <= 0 or not Npc(hireling.cid))
		if hireling.active == HIRELING_ACTIVE_LAMP_OWED or stranded then
			if self:findHirelingLamp(hireling:getId()) then
				-- Already has a lamp in the inbox (a half-completed return); just fix the row.
				hireling.active = 0
				hireling.cid = -1
				hireling:setPosition({ x = 0, y = 0, z = 0 })
				hireling:save()
			else
				local lamp = addHirelingLampToInbox(self, hireling)
				if lamp then
					hireling.active = 0
					hireling.cid = -1
					hireling:setPosition({ x = 0, y = 0, z = 0 })
					if hireling:save() then
						delivered = delivered + 1
						self:sendTextMessage(MESSAGE_EVENT_ADVANCE, hireling:getName() .. "'s lamp has been placed in your Store Inbox.")
					else
						lamp:remove()
						logError("[Hireling] Could not save hireling id " .. tostring(hireling:getId()) .. " after delivering an owed lamp.")
					end
				else
					self:sendTextMessage(MESSAGE_FAILURE, "Your Store Inbox is full, so " .. hireling:getName() .. "'s lamp could not be delivered. Make room and relog.")
				end
			end
		end
	end
	return delivered
end

function Player:findHirelingLamp(hirelingId)
	local inbox = self:getStoreInbox()
	if not inbox then
		return nil
	end

	for i = 0, inbox:getSize() - 1 do
		local item = inbox:getItem(i)
		if item and item:getId() == HIRELING_LAMP and item:getCustomAttribute("Hireling") == hirelingId then
			return item
		end
	end
	return nil
end

-- Kept for callers that ask "does this character have a hireling who can do X"
-- rather than asking about one hireling. Jobs themselves live per hireling
-- (see Hireling:hasSkill), so this is an ANY across the character's hirelings.
function Player:hasHirelingSkill(skillName)
	for _, hireling in ipairs(self:getHirelings()) do
		if hireling:hasSkill(skillName) then
			return true
		end
	end
	return false
end

function Player:hasHirelingOutfit(outfitName)
	return self:kv():scoped("hireling-outfits"):get(outfitName) == true
end

function Player:enableHirelingOutfit(outfitName)
	local outfitScoped = self:kv():scoped("hireling-outfits")
	if outfitScoped:get(outfitName) then
		return false
	end
	outfitScoped:set(outfitName, true)
	return true
end

function Player:clearAllHirelingStats()
	-- Jobs and signs are per hireling now, so clear each one's scope rather
	-- than a single shared list.
	local skillsScoped = self:kv():scoped("hireling-skills")
	local signsScoped = self:kv():scoped("hireling-signs")
	local wornScoped = self:kv():scoped("hireling-worn-signs")
	for _, hireling in ipairs(self:getHirelings()) do
		local id = tostring(hireling:getId())
		local hirelingScope = skillsScoped:scoped(id)
		for _, skill in pairs(HIRELING_SKILLS) do
			hirelingScope:set(skill[2], false)
		end

		local signScope = signsScoped:scoped(id)
		for _, sign in ipairs(HIRELING_SIGNS) do
			if sign.item ~= 0 then
				signScope:set(sign.key, false)
			end
		end
		wornScoped:scoped(id):set("sign", "none")
	end

	local outfitsScoped = self:kv():scoped("hireling-outfits")
	for _, outfit in pairs(HIRELING_OUTFITS) do
		outfitsScoped:set(outfit[2], false)
	end
end
